### ISSUE TITLE
Support for Raspberry pi 4

### ISSUE THREAD

**Issue by adremides** [jack3898/discord-youtube-bot-2#17]
Seems like @discordjs/opus doesn't have the binary pre compiled to work with arm64v8.

Some changes in Dockerfile do the magic but image grows a lot due to the need of building tools.

Made an issue in the repo of discordjs/opus: [Support for Raspberry pi 4](https://github.com/discordjs/opus/issues/129)

# Dockerfile
```dockerfile
FROM arm64v8/node:16-alpine

# Install python/pip
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools
RUN apk add --update --no-cache make gcc g++

ENV NODE_ENV production

WORKDIR /home/node

COPY --chown=node:node . .

RUN npm i @discordjs/opus

USER node

RUN npm i

CMD ["npm", "run", "bot"];
```
# docker-compose.yml
```yaml
version: '3'

services:
  redis:
    container_name: youtube-bot-redis
    image: arm64v8/redis
    sysctls:
      - net.core.somaxconn=1024
    restart: always

  bot:
    image: youtube-bot:latest
    container_name: youtube-bot
    depends_on:
      - redis
    build: .
    restart: always
```

I'm not very good at Docker or Nodejs, so any improvment in this solution is very welcome!
